name: Build image – api

on:
  push:
    branches: [master]
    paths:
      - "build-target.sh"
      - "packages/k8s/**"
      - "packages/api/**"
      - "scripts/*.image.sh"
      - ".github/workflows/image-api.yaml"
  workflow_dispatch:
env:
  SERVICE: api
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - run: chmod +x ./scripts/run.image.sh; ./scripts/run.image.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_SERVER_URL: ${{ github.server_url }}
          GITHUB_REPOSITORY: ${{ github.repository }}
