name: Push manifest – api

on:
  push:
    branches: [master]
    paths:
      - "manifest.sh"
      - "packages/k8s/**"
      - "packages/api/**"
      - "scripts/manifest.sh"
      - "scripts/*.manifest.sh"
      - ".github/workflows/k8s-api.yaml"
  workflow_dispatch:

env:
  SERVICE: api
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}

jobs:
  manifest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    container: node:22-alpine
    steps:
      - uses: actions/checkout@v4
      - run: chmod +x ./scripts/run.manifest.sh; ./scripts/run.manifest.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_SERVER_URL: ${{ github.server_url }}
          GITHUB_REPOSITORY: ${{ github.repository }}
