name: Push manifest – api

on:
  push:
    branches: [main]
    paths:
      - "manifest.sh"
      - "packages/k8s/**"
      - "packages/api/**"
      - ".github/workflows/k8s-api.yml"
  workflow_dispatch:

env:
  SERVICE: api
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}

jobs:
  manifest:
    runs-on: ubuntu-latest
    container: ghcr.io/oras-project/oras:v1.2.2
    steps:
      - uses: actions/checkout@v4
      - run: chmod +x ./manifest.sh; ./manifest.sh
